# Generated by Django 5.2.1 on 2025-05-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0002_rename_title_journal_journal_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('phase', models.CharField(choices=[('new', 'New Submission Consideration'), ('initial_review', 'Initial Review'), ('plagiarism', 'Plagiarism Check'), ('desk_review', 'Desk Review'), ('peer_review', 'Double Blind Peer Review'), ('decision', 'Decision Making'), ('response', 'Author’s Response'), ('publishing', 'Publishing Process')], default='new', max_length=30)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('author_revision', 'Author’s Revision'), ('rejected', 'Rejected'), ('publication', 'Publication Process')], default='in_progress', max_length=30)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('last_action_date', models.DateField(auto_now=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('co_authors', models.ManyToManyField(blank=True, related_name='coauthored_submissions', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal')),
            ],
        ),
    ]
