# Generated by Django 5.2.1 on 2025-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='journal_title',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='summary',
        ),
        migrations.AddField(
            model_name='journal',
            name='founder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='issn_online',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='issn_print',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='issued_since_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='issued_since_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50),
        ),
    ]
